In [2]:
import pandas as pd

# Load CSV
df = pd.read_csv("Detailed_data_dataset.csv")

# Preview first few rows
df.head()

,Staff_Id,Bed_ID,Dpt_ID,Patient_ID,Name,Gender,City,State,Age,Patient_Type,...,Treatemen_Cost,Bed,LOS,ER_Time,Admission_Dates,Feedback,Rating,Age_Bucket,Custom,FZ_Me
0,30016,NaN,108,278,Allen Savannah,Female,Oxford,California,7,outpatient,...,274.48,NaN,0,23.0,16/10/2007,Fully Agree,5,6-20Y,Null,Postive
1,30032,NaN,108,294,Alonso Arthur,Male,Chula Vista,England,43,outpatient,...,274.48,NaN,0,30.0,01/11/2007,Fully Agree,5,41-60y,Null,Postive
2,30040,NaN,108,302,Alonso Carrie,Female,Royal Oak,Seine (Paris),2,outpatient,...,274.48,NaN,0,36.0,09/11/2007,Fully Agree,5,Below 6Y,Null,Postive
3,30046,NaN,108,308,Alonso Danny,Male,Royal Oak,Queensland,8,outpatient,...,274.48,NaN,0,50.0,15/11/2007,Fully Agree,5,6-20Y,Null,Postive
4,30052,NaN,108,314,Alonso Diane,Female,Royal Oak,New South Wales,14,outpatient,...,274.48,NaN,0,48.0,21/11/2007,Fully Agree,5,6-20Y,Null,Postive

In [5]:
df.columns

Index(['Staff_Id', 'Bed_ID', 'Dpt_ID', 'Patient_ID', 'Name', 'Gender', 'City',
       'State', 'Age', 'Patient_Type', 'Status', 'Treatemen_Cost', 'Bed',
       'LOS', 'ER_Time', 'Admission_Dates', 'Feedback', 'Rating', 'Age_Bucket',
       'Custom', 'FZ_Me'],
      dtype='str')

In [6]:
df.shape

(2506, 21)

In [18]:
df.dtypes

Staff_Id             int64
Bed_ID             float64
Dpt_ID               int64
Patient_ID           int64
Name                   str
Gender                 str
City                   str
State                  str
Age                  int64
Patient_Type           str
Status                 str
Treatemen_Cost     float64
Bed                    str
LOS                  int64
ER_Time            float64
Admission_Dates        str
Feedback               str
Rating               int64
Age_Bucket             str
Custom                 str
FZ_Me                  str
dtype: object

In [10]:
df.isnull().sum()

Staff_Id             0
Bed_ID             755
Dpt_ID               0
Patient_ID           0
Name                 0
Gender               0
City                 0
State                0
Age                  0
Patient_Type         0
Status               0
Treatemen_Cost       0
Bed                755
LOS                  0
ER_Time            719
Admission_Dates      0
Feedback             0
Rating               0
Age_Bucket           0
Custom               0
FZ_Me                0
dtype: int64

In [12]:
df.describe()

,Staff_Id,Bed_ID,Dpt_ID,Patient_ID,Age,Treatemen_Cost,LOS,ER_Time,Rating
count,2506.000000,1751.000000,2506.000000,2506.000000,2506.000000,2506.000000,2506.000000,1787.000000,2506.000000
mean,30128.133679,21321.195317,107.322825,1255.103352,30.497207,161.407877,1.697127,65.631226,4.867917
std,75.319520,685.398293,2.244695,725.474113,20.867843,225.478209,2.510109,52.086907,0.635378
min,30001.000000,20001.000000,101.000000,1.000000,1.000000,2.540000,0.000000,11.000000,1.000000
25%,30063.000000,20955.500000,107.000000,628.250000,18.000000,14.280000,0.000000,35.000000,5.000000
50%,30126.000000,21393.000000,108.000000,1254.500000,21.000000,44.730000,2.000000,35.000000,5.000000
75%,30193.000000,21830.500000,109.000000,1880.750000,52.000000,274.480000,2.000000,89.000000,5.000000
max,30262.000000,22844.000000,110.000000,4126.000000,98.000000,1241.330000,32.000000,190.000000,5.000000

In [14]:
df.describe(include="object")

C:\Users\makwa\AppData\Local\Temp\ipykernel_26456\3764884355.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Name,Gender,City,State,Patient_Type,Status,Bed,Admission_Dates,Feedback,Age_Bucket,Custom,FZ_Me
count,2506,2506,2506,2506,2506,2506,1751,2506,2506,2506,2506,2506
unique,2497,2,16,37,2,5,1,361,5,5,7,3
top,Barnes Abigail,Female,Langford,British Columbia,Inpatient,Normal,Occupied,10/03/2007,Fully Agree,6-20Y,1-2D,Postive
freq,2,1280,549,977,1679,1636,1751,77,1828,794,1483,2396

In [16]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.nunique()

Staff_Id            262
Bed_ID             1751
Dpt_ID               10
Patient_ID         2506
Name               2497
Gender                2
City                 16
State                37
Age                  94
Patient_Type          2
Status                5
Treatemen_Cost      165
Bed                   1
LOS                  16
ER_Time              62
Admission_Dates     361
Feedback              5
Rating                4
Age_Bucket            5
Custom                7
FZ_Me                 3
dtype: int64

In [25]:
# Install dependencies (run once)
# !pip install sqlalchemy pymysql cryptography

from sqlalchemy import create_engine, text
import pandas as pd

# 1. Connect to MySQL server

user = "root"
password = "password"
host = "localhost"
port = 3306
database = "Hosptial"
table_name = "patient"

engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}")


# 2. Create database if not exists

with engine.connect() as conn:
    conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {database};"))


# 3. Connect to the database

engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")


# 4. Check if table exists

with engine.connect() as conn:
    result = conn.execute(
        text("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = :db
            AND table_name = :table
        """),
        {"db": database, "table": table_name}
    )
    table_exists = result.scalar() > 0


# 5. If table exists → print it
#    Else → insert dataframe

if table_exists:
    print("Table already exists. Preview:")
    display(pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", engine))
else:
    df.to_sql(table_name, engine, if_exists="replace", index=False)
    print("Table created and data inserted successfully.")
    display(pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", engine))

Table created and data inserted successfully.

,Staff_Id,Bed_ID,Dpt_ID,Patient_ID,Name,Gender,City,State,Age,Patient_Type,...,Treatemen_Cost,Bed,LOS,ER_Time,Admission_Dates,Feedback,Rating,Age_Bucket,Custom,FZ_Me
0,30016,None,108,278,Allen Savannah,Female,Oxford,California,7,outpatient,...,274.48,None,0,23.0,16/10/2007,Fully Agree,5,6-20Y,Null,Postive
1,30032,None,108,294,Alonso Arthur,Male,Chula Vista,England,43,outpatient,...,274.48,None,0,30.0,01/11/2007,Fully Agree,5,41-60y,Null,Postive
2,30040,None,108,302,Alonso Carrie,Female,Royal Oak,Seine (Paris),2,outpatient,...,274.48,None,0,36.0,09/11/2007,Fully Agree,5,Below 6Y,Null,Postive
3,30046,None,108,308,Alonso Danny,Male,Royal Oak,Queensland,8,outpatient,...,274.48,None,0,50.0,15/11/2007,Fully Agree,5,6-20Y,Null,Postive
4,30052,None,108,314,Alonso Diane,Female,Royal Oak,New South Wales,14,outpatient,...,274.48,None,0,48.0,21/11/2007,Fully Agree,5,6-20Y,Null,Postive